### ISSUE TITLE
KeePassWin doesn't synchronize with Dropbox/kdbx

### ISSUE THREAD

**Issue by robrij** [twsouthwick/KeePassWin#48]
On my Windows Phone the KeePass databases stored on Dropbox are not automatically synced on my phone.

Any idea why and mabey a solution?

Windows Phone Mobile
Update 1607
Build 10.0.15.14.1000

**Comment by twsouthwick** [comment]
I've had trouble in the past with mobile and syncing. I was hoping to use the built in file pickers and the caching service they provide, but OneDrive doesn't work at all with it, and Dropbox is hit and miss. 

For now, the way I do it is consider it read only and remove it (hold down on the icon and click 'Remove') and add it again when I want an update.

This is far from perfect, but I'm wary of adding specific providers. I'll try to take a closer look at this to see how this can be enabled.
